# Generated by Django 2.0.7 on 2019-07-25 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_destination_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
